# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Runs tests for 0-1 series and series with a given median.
#' 
#' @param run 0-1 series. If median is used, it can be any series to test its randomness.
#' @param median The defaulted value is 0.200164, it means nothing.
#' @param bigdata if the repetition of any element is over 16, it's better to set it as true. Here, central limit theorem will be applied to replace hyper-geometric distribution.
#' @return The p-value of a one-sided test.
#' @references 
#' Friedman J H, Rafsky L C. Multivariate generalizations of the Wald-Wolfowitz and Smirnov two-sample tests[J]. The Annals of Statistics, 1979: 697-717.
#' @examples
#' library(KuangTest)
#' a=c(1,0,0,0,1,1,0,1,0,0,1,0,0,1,1,1)
#' kuangtest(a)   
#' b=c(0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1)
#' kuangtest(b)
#' c<- c(5.36, 5.29, 5.58, 5.65, 5.57, 5.53, 5.62, 5.29, 5.44, 5.34, 5.79, 5.10)
#' kuangtest(c,median = median(c))
#' d<-c(1,0,0,0,1,1,0,1,0,0,1,0,0,1,1,1,0,0,0,1,1,0,1,0,0,1,0,0,1,1,1,0,0,0,1,1,0,1)
#' kuangtest(d,bigdata = TRUE)
kuangtest <- function(run, median = 0.200164, bigdata = FALSE) {
    .Call(`_KuangTest_kuangtest`, run, median, bigdata)
}

#' Runs tests for 1-n series with repetition. This test is designed to judge the fairness of ranks.
#' 
#' @param rank 1-n series with repetition. 
#' @param max number of n.
#' @param method This test will generate many independent p-values according to each pair, Methods are used to adjust the level of significance.
#' @param alpha The defaulted value is 0.05.
#' @return The p-value of each one-sided test. Plus, A matrix contains each pair and whether we should reject H0 considering their p-values and the level of significance.
#' @references 
#' Friedman J H, Rafsky L C. Multivariate generalizations of the Wald-Wolfowitz and Smirnov two-sample tests[J]. The Annals of Statistics, 1979: 697-717.
#' 
#' Bonferroni, C. E. "Il calcolo delle assicurazioni su gruppi di teste." In Studi in Onore del Professore Salvatore Ortu Carboni. Rome: Italy, pp. 13-60, 1935.
#' 
#' Benjamini, Yoav, and Yosef Hochberg. "Controlling the false discovery rate: a practical and powerful approach to multiple testing." Journal of the Royal statistical society: series B (Methodological) 57.1 (1995): 289-300.
#' @examples
#' library(KuangTest)
#' test<-c(1,3,3,3,1,1,3,1,3,3,1,3,3,1,1,4,2,4,2,2,4,4,2,2,4,4,2,2,4,4,2,2,4,4,2)
#' Kfairnesstest(rank =test, max = 4,method = "BH")
#' Kfairnesstest(rank =test, max = 4,method = "B")
Kfairnesstest <- function(rank, max, method = "Bonferroni", alpha = 0.05) {
    .Call(`_KuangTest_Kfairnesstest`, rank, max, method, alpha)
}

